name: Python Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo
          pip install python-telegram-bot
          pip install pyTelegramBotAPI
          pip install certifi
          pip install pytz
          pip install telebot pymongo aiohttp
          pip install pymongo python-telegram-bot pyTelegramBotAPI certifi
          pip install flask
          pip3 install flask

      - name: Set Execute Permissions
        run: chmod +x * && chmod +x bgmi

      - name: Run Application
        run: python s.py
